spring:
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates/
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 123456
      open-in-view: true